#!/bin/sh
# mkwww.sh - turn the www/ front-panel assets into a C header of byte
# arrays plus a lookup table, so pdp11-hostd is one self-contained binary.
#
# That matters here: scripts/deploy_pdp11_hostd.sh installs the daemon by
# copying a single ARM ELF onto the board. Serving the UI from files under
# /usr/share would silently give you a stale page (or none) after every
# quick redeploy, which is exactly the fast loop this project lives on.
# The -W option still serves from a directory when you want to iterate on
# the CSS without rebuilding.
#
# Only shell + coreutils (od/sed/tr) - no xxd, no host compiler, because
# this has to run inside bitbake's do_compile for the ARM target.
#
#   usage: mkwww.sh <out.h> <file>...

set -eu

out=$1
shift

{
    echo "/* generated by mkwww.sh - do not edit */"
    echo "#ifndef WWW_DATA_H"
    echo "#define WWW_DATA_H"
    echo

    for f in "$@"; do
        base=$(basename "$f")
        sym=$(printf '%s' "$base" | tr -c 'A-Za-z0-9' '_')
        echo "static const unsigned char www_$sym[] = {"
        # -v keeps runs of identical bytes (no "*" elision); one decimal
        # byte per column, re-emitted as a comma list.
        od -An -v -tu1 < "$f" | sed -e 's/^ *//' -e 's/  */,/g' -e 's/^/ /' -e 's/$/,/' \
                              | sed -e 's/ ,/ /'
        echo "};"
        echo
    done

    echo "static const struct www_file {"
    echo "    const char          *path;"
    echo "    const char          *ctype;"
    echo "    const unsigned char *data;"
    echo "    unsigned             len;"
    echo "} www_files[] = {"
    for f in "$@"; do
        base=$(basename "$f")
        sym=$(printf '%s' "$base" | tr -c 'A-Za-z0-9' '_')
        case "$base" in
            *.html) ct="text/html; charset=utf-8" ;;
            *.css)  ct="text/css; charset=utf-8" ;;
            *.js)   ct="application/javascript; charset=utf-8" ;;
            *.svg)  ct="image/svg+xml" ;;
            *.json) ct="application/json" ;;
            *.png)  ct="image/png" ;;
            *.ico)  ct="image/x-icon" ;;
            *)      ct="application/octet-stream" ;;
        esac
        printf '    { "/%s", "%s", www_%s, (unsigned)sizeof(www_%s) },\n' \
               "$base" "$ct" "$sym" "$sym"
    done
    echo "};"
    echo
    echo "#define WWW_NFILES ((int)(sizeof(www_files) / sizeof(www_files[0])))"
    echo
    echo "#endif /* WWW_DATA_H */"
} > "$out"
